#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""esp32-node 一键构建脚本（对标 esp32-xiaozhi 的 scripts/build.py，按项目裁剪）。

前置条件：在已初始化的 ESP-IDF shell 中运行（idf.py 在 PATH、IDF_PATH 已设置）：
    Windows: ESP-IDF PowerShell/CMD 快捷方式
    Linux:   . $IDF_PATH/export.sh

用法:
    python release.py --list
    python release.py <项目名> [--flash] [--monitor] [-p|--port 端口]

示例:
    python release.py --list
    python release.py c3_oled_thp
    python release.py s3_tft_fan --flash -p COM7
    python release.py c3_oled_voc --flash --monitor -p COM7

机制:
    读 main/projects/<项目>/config.json 的 target 与 builds[0].sdkconfig_append，
    生成 build/node-build.sdkconfig.defaults 片段，拼接到根 sdkconfig.defaults 之后，
    通过 idf.py reconfigure -DIDF_TARGET=... -DSDKCONFIG_DEFAULTS=... 一次完成
    目标芯片切换与项目配置，然后 idf.py build。
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parent
PROJECTS_DIR = REPO_ROOT / "main" / "projects"
SDKCONFIG = REPO_ROOT / "sdkconfig"
BUILD_DIR = REPO_ROOT / "build"
FRAGMENT_REL = Path("build/node-build.sdkconfig.defaults")  # CMake 接收相对路径（正斜杠）
BASE_DEFAULTS_REL = Path("sdkconfig.defaults")

PROJECT_MACRO_RE = re.compile(r"^(CONFIG_NODE_PROJECT_\w+)=y$")
PORT_RE = re.compile(r"^[A-Za-z0-9_./-]+$")


def fail(msg: str) -> None:
    print(f"[release.py][ERROR] {msg}", file=sys.stderr)
    sys.exit(1)


def info(msg: str) -> None:
    print(f"[release.py] {msg}")


def list_projects() -> List[str]:
    if not PROJECTS_DIR.is_dir():
        fail(f"项目目录不存在: {PROJECTS_DIR}")
    return sorted(p.parent.name for p in PROJECTS_DIR.glob("*/config.json"))


def load_project(name: str) -> dict:
    cfg_path = PROJECTS_DIR / name / "config.json"
    if not cfg_path.is_file():
        fail(f"项目 {name!r} 不存在: {cfg_path}\n可用项目: {', '.join(list_projects())}")
    with cfg_path.open(encoding="utf-8") as f:
        cfg = json.load(f)

    target = cfg.get("target")
    if not target:
        fail(f"{cfg_path}: 缺少 target 字段")
    builds = cfg.get("builds")
    if not builds or not isinstance(builds, list):
        fail(f"{cfg_path}: 缺少非空 builds 数组")
    append = builds[0].get("sdkconfig_append", [])
    if not isinstance(append, list) or not append:
        fail(f"{cfg_path}: builds[0].sdkconfig_append 必须是非空数组")

    macros = [item.split("=", 1)[0]
              for item in append
              if PROJECT_MACRO_RE.match(item.strip())]
    if len(macros) != 1:
        fail(f"{cfg_path}: sdkconfig_append 中必须恰好包含一个 CONFIG_NODE_PROJECT_*=y，"
             f"实际: {macros}")
    cfg["_project_macro"] = macros[0]
    cfg["_append"] = [item.strip() for item in append]
    cfg["_path"] = cfg_path
    return cfg


def read_configured_target() -> Optional[str]:
    """从现有 sdkconfig 读取已配置的 IDF_TARGET；不存在返回 None。"""
    if not SDKCONFIG.is_file():
        return None
    m = re.search(r'^CONFIG_IDF_TARGET="([^"]+)"$',
                  SDKCONFIG.read_text(encoding="utf-8", errors="replace"),
                  re.MULTILINE)
    return m.group(1) if m else None


def sdkconfig_symbol_is(symbol: str, value: str) -> bool:
    if not SDKCONFIG.is_file():
        return False
    text = SDKCONFIG.read_text(encoding="utf-8", errors="replace")
    return re.search(rf"^{re.escape(symbol)}={re.escape(value)}$",
                     text, re.MULTILINE) is not None


def run_idf(*args: str) -> None:
    cmd = " ".join(("idf.py", *args))
    info(f"$ {cmd}")
    try:
        subprocess.run(cmd, shell=True, cwd=REPO_ROOT, check=True)
    except FileNotFoundError:
        fail("找不到 idf.py。请在已初始化的 ESP-IDF shell 中运行本脚本 "
             "(Windows 用 ESP-IDF PowerShell，Linux 先 . $IDF_PATH/export.sh)。")
    except subprocess.CalledProcessError as e:
        fail(f"命令执行失败(exit={e.returncode}): {cmd}")


def write_fragment(append: List[str]) -> None:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    fragment = BUILD_DIR / FRAGMENT_REL.name
    fragment.write_text(
        "# Generated by release.py — 请勿手改，来源: main/projects/<项目>/config.json\n"
        + "\n".join(append)
        + "\n",
        encoding="utf-8",
    )
    info(f"已生成配置片段: {FRAGMENT_REL.as_posix()} ({len(append)} 项)")


def configure(cfg: dict) -> None:
    target = cfg["target"]
    old_target = read_configured_target()

    # 跨 target 必须清空 build/ 与 sdkconfig，否则 CMake 缓存污染导致配置失败
    if old_target is not None and old_target != target:
        info(f"目标芯片切换: {old_target} -> {target}，清理 build/ 与 sdkconfig")
        if BUILD_DIR.is_dir():
            shutil.rmtree(BUILD_DIR)

    # 每次构建都让 config.json 的 append 完整重新生效（config.json 是配置唯一事实源）；
    # 旧 sdkconfig 备份为 sdkconfig.old，与 esp32-xiaozhi build.py 行为一致。
    if SDKCONFIG.is_file():
        old = SDKCONFIG.with_name("sdkconfig.old")
        if old.is_file():
            old.unlink()
        SDKCONFIG.replace(old)

    write_fragment(cfg["_append"])

    defaults = ";".join((BASE_DEFAULTS_REL.as_posix(), FRAGMENT_REL.as_posix()))
    run_idf(f"-DIDF_TARGET={target}",
            f'-DSDKCONFIG_DEFAULTS="{defaults}"',
            "reconfigure")

    # 配置后校验：target 与项目宏必须按 config.json 落地，防止 json/Kconfig 名字写错
    if not sdkconfig_symbol_is("CONFIG_IDF_TARGET", f'"{target}"'):
        fail(f"Kconfig 未接受目标芯片 {target}，请检查 sdkconfig")
    if not sdkconfig_symbol_is(cfg["_project_macro"], "y"):
        fail(f"Kconfig 未接受项目宏 {cfg['_project_macro']}=y，"
             f"请检查 {cfg['_path']} 与 main/Kconfig.projbuild 是否一致")
    info(f"配置校验通过: target={target}, {cfg['_project_macro']}=y")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="esp32-node 项目一键构建（在 ESP-IDF shell 中运行）",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("project", nargs="?", help="项目名（main/projects 下的目录名）")
    parser.add_argument("--list", action="store_true", help="列出全部项目后退出")
    parser.add_argument("--flash", action="store_true", help="构建成功后烧录")
    parser.add_argument("--monitor", action="store_true", help="烧录后进入串口监视（需配合 --flash 或已烧录）")
    parser.add_argument("-p", "--port", help="串口号，如 COM7 / /dev/ttyUSB0")
    args = parser.parse_args()

    if args.list:
        projects = list_projects()
        print("可用项目:")
        for name in projects:
            cfg = load_project(name)
            print(f"  {name:<16} target={cfg['target']:<10} {cfg.get('type', '')}")
        return

    if not args.project:
        parser.print_help()
        fail("缺少项目名。用 --list 查看可用项目。")

    if args.port and not PORT_RE.match(args.port):
        fail(f"非法端口名: {args.port}")

    cfg = load_project(args.project)
    info(f"项目: {args.project}  type={cfg.get('type')}  target={cfg['target']}")

    configure(cfg)
    run_idf("build")

    actions = []
    if args.flash:
        actions.append("flash")
    if args.monitor:
        actions.append("monitor")
    if actions:
        port_args = ["-p", args.port] if args.port else []
        run_idf(*port_args, *actions)
    else:
        info("构建完成。如需烧录: python release.py "
             f"{args.project} --flash -p <端口>")


if __name__ == "__main__":
    main()
